// ══ DATA ══
const PI = {
  a: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80",
  b: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80",
  c: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&q=80",
  d: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&q=80",
  e: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
  f: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=600&q=80",
  g: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
  h: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
  i: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
};
const properties = [
  {
    id: 1,
    price: "£825,000",
    priceN: 825000,
    type: "Detached House",
    addr: "123 Oakridge Drive, Streatham, London, SW16 4XX",
    beds: 4,
    baths: 3,
    sqft: 2450,
    badge: "sale",
    img: PI.a,
    new: true,
    epc: "C",
    features: [
      "South-facing garden",
      "Off-street parking",
      "Renovated kitchen",
      "Close to Streatham Common",
    ],
    desc: "A handsome four-bedroom detached home on a quiet road in Streatham, with a bright open-plan kitchen and a private south-facing garden.",
  },
  {
    id: 2,
    price: "£3,200/mo",
    priceN: 3200,
    type: "Terraced House",
    addr: "742 Maple Street, Bristol, BS1 1AA",
    beds: 3,
    baths: 2,
    sqft: 1800,
    badge: "rent",
    img: PI.b,
    new: false,
    epc: "D",
    features: [
      "Furnished",
      "Period features",
      "Courtyard garden",
      "Central location",
    ],
    desc: "A characterful three-bedroom terrace in the heart of Bristol, available furnished and ready to move into.",
  },
  {
    id: 3,
    price: "£420,000",
    priceN: 420000,
    type: "Semi-Detached House",
    addr: "88 Harbour View Drive, Didsbury, Manchester, M20 2AA",
    beds: 3,
    baths: 2,
    sqft: 1250,
    badge: "sale",
    img: PI.c,
    new: true,
    epc: "C",
    features: [
      "Driveway",
      "Modern bathroom",
      "Near Metrolink",
      "Landscaped garden",
    ],
    desc: "A well-presented semi in leafy Didsbury, ideal for families and a short walk from the Metrolink.",
  },
  {
    id: 4,
    price: "£540,000",
    priceN: 540000,
    type: "Bungalow",
    addr: "19 Pinecrest Lane, Leeds, LS8 1AA",
    beds: 3,
    baths: 1,
    sqft: 1600,
    badge: "sold",
    img: PI.d,
    new: false,
    epc: "D",
    features: ["Single storey", "Large plot", "Garage", "Quiet cul-de-sac"],
    desc: "A spacious detached bungalow on a generous plot in north Leeds.",
  },
  {
    id: 5,
    price: "£525,000",
    priceN: 525000,
    type: "Flat",
    addr: "47 Birchwood Close, Brixton, London, SW2 1AA",
    beds: 2,
    baths: 2,
    sqft: 1000,
    badge: "sale",
    img: PI.e,
    new: true,
    epc: "B",
    features: [
      "Private balcony",
      "Concierge",
      "Residents gym",
      "Walk to Brixton Tube",
    ],
    desc: "A bright two-bed apartment moments from Brixton\u2019s buzz, with a private balcony and on-site gym.",
  },
  {
    id: 6,
    price: "£575,000",
    priceN: 575000,
    type: "Terraced House",
    addr: "23 Garden Walk, Walthamstow, London, E17 1AA",
    beds: 3,
    baths: 2,
    sqft: 1550,
    badge: "sale",
    img: PI.f,
    new: false,
    epc: "C",
    features: [
      "Loft conversion",
      "Period features",
      "Near Walthamstow Village",
      "Garden studio",
    ],
    desc: "A characterful Victorian terrace with a loft conversion and garden studio, close to Walthamstow Village.",
  },
  {
    id: 7,
    price: "£1,800/mo",
    priceN: 1800,
    type: "Flat",
    addr: "15 City Lofts, Birmingham, B1 1AA",
    beds: 1,
    baths: 1,
    sqft: 650,
    badge: "rent",
    img: PI.g,
    new: true,
    epc: "B",
    features: [
      "City-centre views",
      "Concierge",
      "Furnished",
      "Bills-included option",
    ],
    desc: "A stylish one-bed loft apartment in central Birmingham with skyline views.",
  },
  {
    id: 8,
    price: "£950,000",
    priceN: 950000,
    type: "Detached House",
    addr: "7 The Green, Oxford, OX2 1AA",
    beds: 5,
    baths: 4,
    sqft: 3200,
    badge: "sale",
    img: PI.h,
    new: false,
    epc: "C",
    features: [
      "Double garage",
      "Studio annexe",
      "Mature garden",
      "Top school catchment",
    ],
    desc: "A substantial five-bedroom family home in north Oxford with an annexe and beautiful gardens.",
  },
  {
    id: 9,
    price: "£465,000",
    priceN: 465000,
    type: "Detached House",
    addr: "3 Headland Road, Newquay, Cornwall, TR7 1AA",
    beds: 4,
    baths: 2,
    sqft: 1700,
    badge: "sale",
    img: PI.a,
    new: true,
    epc: "C",
    features: [
      "Sea glimpses",
      "Sunny garden",
      "Driveway",
      "Near Fistral Beach",
    ],
    desc: "A modern detached home a short stroll from Fistral Beach, with sea glimpses and a sunny garden.",
  },
  {
    id: 10,
    price: "£385,000",
    priceN: 385000,
    type: "Cottage",
    addr: "11 Quay Steps, Falmouth, Cornwall, TR11 1AA",
    beds: 2,
    baths: 1,
    sqft: 900,
    badge: "sold",
    img: PI.i,
    new: false,
    epc: "E",
    features: ["Harbour views", "Period cottage", "Courtyard", "Town centre"],
    desc: "A charming harbourside cottage in the heart of Falmouth.",
  },
  {
    id: 11,
    price: "£345,000",
    priceN: 345000,
    type: "Flat",
    addr: "42 Hyndland Road, West End, Glasgow, G12 9AA",
    beds: 3,
    baths: 1,
    sqft: 1100,
    badge: "sale",
    img: PI.e,
    new: true,
    epc: "C",
    features: [
      "Period tenement",
      "High ceilings",
      "Bay windows",
      "Near Botanic Gardens",
    ],
    desc: "A classic West End tenement flat with original features, close to the Botanic Gardens.",
  },
  {
    id: 12,
    price: "£1,250/mo",
    priceN: 1250,
    type: "Flat",
    addr: "9 Merchant Square, Glasgow, G1 1AA",
    beds: 2,
    baths: 1,
    sqft: 780,
    badge: "rent",
    img: PI.g,
    new: false,
    epc: "B",
    features: ["Furnished", "City centre", "Secure entry", "Modern kitchen"],
    desc: "A modern two-bed flat in Glasgow\u2019s Merchant City, available furnished.",
  },
  {
    id: 13,
    price: "£399,000",
    priceN: 399000,
    type: "Townhouse",
    addr: "6 Mermaid Quay, Cardiff Bay, Cardiff, CF10 1AA",
    beds: 3,
    baths: 3,
    sqft: 1500,
    badge: "sale",
    img: PI.c,
    new: true,
    epc: "B",
    features: ["Waterfront", "Garage", "Roof terrace", "Near the barrage"],
    desc: "A contemporary waterfront townhouse in Cardiff Bay with a roof terrace and garage.",
  },
  {
    id: 14,
    price: "£1,500/mo",
    priceN: 1500,
    type: "Terraced House",
    addr: "28 Cathedral Road, Pontcanna, Cardiff, CF11 9AA",
    beds: 3,
    baths: 2,
    sqft: 1300,
    badge: "rent",
    img: PI.b,
    new: false,
    epc: "D",
    features: ["Period features", "Near Bute Park", "Unfurnished", "Garden"],
    desc: "A handsome period terrace in sought-after Pontcanna, moments from Bute Park.",
  },
  {
    id: 15,
    price: "£695,000",
    priceN: 695000,
    type: "Flat",
    addr: "18 Heriot Row, New Town, Edinburgh, EH3 6AA",
    beds: 3,
    baths: 2,
    sqft: 1450,
    badge: "sale",
    img: PI.h,
    new: true,
    epc: "C",
    features: [
      "Georgian townhouse",
      "Shared gardens",
      "High ceilings",
      "City centre",
    ],
    desc: "An elegant Georgian apartment in Edinburgh\u2019s New Town, with access to private gardens.",
  },
  {
    id: 16,
    price: "£430,000",
    priceN: 430000,
    type: "Flat",
    addr: "5 The Shore, Leith, Edinburgh, EH6 6AA",
    beds: 2,
    baths: 2,
    sqft: 950,
    badge: "sold",
    img: PI.i,
    new: false,
    epc: "C",
    features: [
      "Waterside",
      "Restored warehouse",
      "Exposed brick",
      "Near restaurants",
    ],
    desc: "A stylish warehouse conversion on the Shore in Leith.",
  },
  {
    id: 17,
    price: "£1,150,000",
    priceN: 1150000,
    type: "Terraced House",
    addr: "60 Thornhill Road, Islington, London, N1 1AA",
    beds: 4,
    baths: 2,
    sqft: 1900,
    badge: "sale",
    img: PI.f,
    new: false,
    epc: "D",
    features: [
      "Georgian terrace",
      "Walled garden",
      "Near Upper Street",
      "Original features",
    ],
    desc: "A beautiful four-bedroom Georgian terrace in Islington, steps from Upper Street.",
  },
  {
    id: 18,
    price: "£2,950/mo",
    priceN: 2950,
    type: "Flat",
    addr: "12 Quay House, Canary Wharf, London, E14 1AA",
    beds: 2,
    baths: 2,
    sqft: 980,
    badge: "rent",
    img: PI.g,
    new: true,
    epc: "B",
    features: ["River views", "Concierge", "Gym and pool", "Furnished"],
    desc: "A high-floor two-bed apartment in Canary Wharf with river views and resort-style amenities.",
  },
  {
    id: 19,
    price: "£640,000",
    priceN: 640000,
    type: "Flat",
    addr: "4 Royal York Crescent, Clifton, Bristol, BS8 4AA",
    beds: 2,
    baths: 2,
    sqft: 1150,
    badge: "sale",
    img: PI.e,
    new: true,
    epc: "C",
    features: [
      "Crescent views",
      "Period grandeur",
      "Allocated parking",
      "Near the suspension bridge",
    ],
    desc: "An elegant apartment on Clifton\u2019s famous crescent, with sweeping views.",
  },
  {
    id: 20,
    price: "£510,000",
    priceN: 510000,
    type: "Semi-Detached House",
    addr: "77 Elm Grove, Didsbury, Manchester, M20 6AA",
    beds: 4,
    baths: 2,
    sqft: 1750,
    badge: "sold",
    img: PI.c,
    new: false,
    epc: "C",
    features: ["Extended kitchen", "Driveway", "South garden", "Near schools"],
    desc: "A much-loved family semi in Didsbury with a stylish extension.",
  },
  {
    id: 21,
    price: "€595,000",
    priceN: 595000,
    type: "Villa",
    addr: "Camino del Mar 12, Marbella, Spain",
    beds: 4,
    baths: 3,
    sqft: 2100,
    badge: "sale",
    img: PI.a,
    new: true,
    overseas: true,
    epc: "B",
    features: ["Private pool", "Sea views", "Sun terrace", "Near the beach"],
    desc: "A sun-filled villa near Marbella with a private pool and sweeping sea views.",
  },
  {
    id: 22,
    price: "€385,000",
    priceN: 385000,
    type: "Apartment",
    addr: "Carrer de Mallorca 88, Barcelona, Spain",
    beds: 2,
    baths: 2,
    sqft: 950,
    badge: "sale",
    img: PI.e,
    new: false,
    overseas: true,
    epc: "C",
    features: ["Balcony", "City centre", "Period building", "Near metro"],
    desc: "A stylish apartment in central Barcelona, moments from the metro.",
  },
  {
    id: 23,
    price: "€420,000",
    priceN: 420000,
    type: "Apartment",
    addr: "5 Promenade des Anglais, Nice, France",
    beds: 2,
    baths: 1,
    sqft: 800,
    badge: "sale",
    img: PI.g,
    new: true,
    overseas: true,
    epc: "C",
    features: ["Sea-front", "Balcony", "Recently renovated", "Near old town"],
    desc: "A bright sea-front apartment on the Promenade des Anglais in Nice.",
  },
  {
    id: 24,
    price: "€365,000",
    priceN: 365000,
    type: "Farmhouse",
    addr: "Chemin de la Vallée, Dordogne, France",
    beds: 4,
    baths: 2,
    sqft: 2400,
    badge: "sale",
    img: PI.d,
    new: false,
    overseas: true,
    epc: "D",
    features: [
      "Stone farmhouse",
      "Large garden",
      "Original beams",
      "Rural setting",
    ],
    desc: "A characterful stone farmhouse set in the Dordogne countryside.",
  },
  {
    id: 25,
    price: "€450,000",
    priceN: 450000,
    type: "Villa",
    addr: "Rua da Praia 7, Algarve, Portugal",
    beds: 3,
    baths: 3,
    sqft: 1600,
    badge: "sale",
    img: PI.c,
    new: true,
    overseas: true,
    epc: "B",
    features: ["Private pool", "Sea views", "Terrace", "Near golf"],
    desc: "A modern villa in the Algarve with a pool and sea views.",
  },
  {
    id: 26,
    price: "€330,000",
    priceN: 330000,
    type: "Apartment",
    addr: "Rua Augusta 22, Lisbon, Portugal",
    beds: 2,
    baths: 1,
    sqft: 850,
    badge: "sale",
    img: PI.h,
    new: false,
    overseas: true,
    epc: "C",
    features: ["Historic centre", "Balcony", "Tram nearby", "Renovated"],
    desc: "A characterful apartment in the heart of historic Lisbon.",
  },
];

const passportRecords = [
  {
    date: "20 May 2024",
    title: "Kitchen Refurbishment",
    desc: "Full kitchen refurbishment including new units, worktops, sink, flooring and integrated appliances.",
    cost: "£8,750",
    contractor: "Greenwood Interiors",
    icon: "🔧",
    photos: true,
  },
  {
    date: "15 Feb 2024",
    title: "Exterior Painting",
    desc: "Exterior walls painted including front facade, woodwork and garage door.",
    cost: "£2,200",
    contractor: "BrightShine Decorators",
    icon: "🎨",
    photos: true,
  },
  {
    date: "10 Oct 2023",
    title: "Boiler Replacement",
    desc: "Old boiler removed and new energy-efficient combi boiler installed.",
    cost: "£2,950",
    contractor: "HeatCare Services",
    icon: "💧",
    photos: false,
  },
  {
    date: "05 Jul 2023",
    title: "Electrical Upgrade",
    desc: "Consumer unit upgraded and additional sockets installed in kitchen and living room.",
    cost: "£1,150",
    contractor: "VoltEdge Electrical",
    icon: "⚡",
    photos: false,
  },
  {
    date: "22 Apr 2023",
    title: "Garden Landscaping",
    desc: "New decking area, raised flower beds, and lawn laid.",
    cost: "£3,600",
    contractor: "GreenScape Gardens",
    icon: "🌳",
    photos: true,
  },
];

const savedIds = new Set();

function getItems(){
  return properties;
}